language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
install:
  - npm install
scripts:
  - npm test
  - npm install codecov -g
  - jest --coverage && cat ./coverage/lcov.info
after_success:
  - codecov

jobs:
include:
  - stage: Produce Coverage
    node_js: node
    script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js&& rm -rf ./coverages