language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
install:
  - npm install
scripts:
  - npm test
  - npm install codecov -g
  - jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
after_success:
  - codecov